theme = "darcula-solid"

[editor]
indent-guides.render = true
line-number = "relative"
soft-wrap.enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = true 

[editor.statusline]
left =  ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control"]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-type", "file-encoding"]

[keys.normal]
"esc" = ["keep_primary_selection", "collapse_selection"]

[keys.normal.space]
t = ":format" # Format document

[keys.insert]
"A-b" = "move_prev_word_start"
"A-f" = "move_next_word_start"
"C-b" = "move_char_left"
"C-f" = "move_char_right"
"C-a" = "goto_line_start"
"C-e" = "goto_line_end"
"C-p" = "move_visual_line_up"
"C-n" = "move_visual_line_down"

# Works by default
# C-k - remove from the cursor to end of the line
# C-u - remove from the cursor to start of the line
# C-w - remove a word to the left from the cursor
# C-h - remove a character to the left from the cursor
# A-d - remove a word to the right from the cursor
# C-d - remove a character to the right from the cursor
