theme = "darcula-solid"

[editor]
indent-guides.render = true
line-number = "relative"
smart-tab.enable = false
soft-wrap.enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = true 

[editor.statusline]
left =  ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control"]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-type", "file-encoding"]

[keys.normal.space]
t = ":format" # Format document

[keys.insert]
"A-b" = "move_prev_word_start"
"A-f" = "move_next_word_start"
"C-b" = "move_char_left"
"C-f" = "move_char_right"
"C-a" = "goto_line_start"
"C-e" = "goto_line_end"
"C-p" = "move_visual_line_up"
"C-n" = "move_visual_line_down"
