theme = "darcula-solid"

[editor]
line-number = "relative"
soft-wrap.enable = true
indent-guides.render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true 

[editor.statusline]
left =  ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control"]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-type", "file-encoding"]

[keys.normal.space]
t = ":format" # Format document
