# Languages

[[language]]
name = "fish"
language-servers = [ "efm" ]
auto-format = true

[[language]]
name = "git-commit"
language-servers = [ "efm" ]

[[language]]
name = "javascript"
language-servers = [ "deno", "efm" ]

[[language]]
name = "typescript"
language-servers = [ "deno", "efm" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "efm" ]

[[language]]
name = "python"
language-servers = [ "pylsp", "efm" ]
auto-format = true

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "efm" ]

[[language]]
name = "text"
scope = "text.plain"
file-types = [ "txt" ]
roots = []
language-servers = [ "efm" ]

# Language servers

[language-server.deno]
command = "deno"
args = [ "lsp" ]

[language-server.deno.config.deno]
enable = true
lint = true

[language-server.efm]
command = "efm-langserver"
# efm-langserver configuratin if here:
# https://codeberg.org/AkhIL/config-efm-langserver
# Maybe I will move it here, maybe not

[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.pylint.enabled = true
plugins.pyflakes.enabled = false
plugins.isort.enabled = true
# plugins.rope_autoimport.enabled = true

[language-server.rust-analyzer.config.rust-analyzer]
check.command = "clippy" 
