# Languages

[[language]]
name = "fish"
language-servers = [ "dls" ]

[[language]]
name = "git-commit"
language-servers = [ "dls" ]

[[language]]
name = "javascript"
language-servers = [ "deno", "dls" ]

[[language]]
name = "typescript"
language-servers = [ "deno", "dls" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "dls" ]

[[language]]
name = "python"
language-servers = [ "pylsp", "dls" ]

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "dls" ]

[[language]]
name = "text"
scope = "text.plain"
file-types = [ "txt" ]
roots = []
language-servers = [ "dls" ]

# Language servers

[language-server.deno]
command = "deno"
args = [ "lsp" ]

[language-server.deno.config.deno]
enable = true
lint = true

[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.pylint.enabled = true
plugins.pyflakes.enabled = false
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = true
plugins.rope_autoimport.enabled = true

[language-server.rust-analyzer]
command = "rustup"
args = [ "run", "stable", "rust-analyzer" ]

[language-server.rust-analyzer.config.rust-analyzer]
check.command = "clippy" 

# Diagnostic language server.
# See https://github.com/iamcco/diagnostic-languageserver .

[language-server.dls]
command = "diagnostic-languageserver"
args = [ "--stdio", "--log-level=2" ]

[language-server.dls.config.filetypes]
"*" = "cspell"
fish = "fish"

# CSpell https://cspell.org/docs/getting-started/ .

[language-server.dls.config.linters.cspell]
command = "cspell"
args = [ "lint", "--show-suggestions", "stdin" ]
sourceName = "cspell"
rootPatterns = [
  ".cspell.json",
  "cspell.json",
  ".cSpell.json",
  "cSpell.json",
  "cspell.config.js",
  "cspell.config.cjs",
  "cspell.config.json",
  "cspell.config.yaml",
  "cspell.config.yml",
  "cspell.yaml",
  "cspell.yml",
]
debounce = 1000
formatLines = 1
formatPattern = [
  "^[^:]+:(\\d+):(\\d+) - (.*) \\((.*)\\) (.*): \\[(.*)\\]",
  { line = 1, column = 2, security = 3, message = [ 3, " (", 4, ") [", 6, "]" ] },
]
securities = { "Unknown word" = "warning" }

# Fish shell

[language-server.dls.config.linters.fish]
command = "fish"
args = [ "-n", "%file" ]
isStdout = false
isStderr = true
sourceName = "fish"
onSaveOnly = true 
debounce = 1000
formatLines = 1
formatPattern = [
  "^.*\\(line (\\d+)\\): (.*)$",
  { "line" = 1, "message" = 2 }
]
