# Languages

[[language]]
name = "capnp"
language-servers = [ "codebook" ]

[[language]]
name = "fish"
language-servers = [ "efm", "codebook" ]
auto-format = true

[[language]]
name = "git-commit"
language-servers = [ "codebook" ]

[[language]]
name = "javascript"
language-servers = [ "deno", "codebook" ]

[[language]]
name = "typescript"
language-servers = [ "deno", "codebook" ]

[[language]]
name = "toml"
language-servers = [ "taplo", "codebook" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "codebook" ]

[[language]]
name = "python"
language-servers = [ "ty", "ruff", "pylsp", "codebook" ]
auto-format = true

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "codebook" ]

[[language]]
name = "text"
scope = "text.plain"
file-types = [ "txt" ]
roots = []
language-servers = [ "codebook" ]

# Language servers
 
[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[language-server.deno]
command = "deno"
args = [ "lsp" ]

[language-server.deno.config.deno]
enable = true
lint = true

[language-server.efm]
command = "efm-langserver"
# efm-langserver configuratin is there:
# https://codeberg.org/AkhIL/config-efm-langserver
# Maybe I will move it here, maybe not

[language-server.pylsp.config.pylsp.plugins]
autopep8.enabled = false
pycodestyle.enable = false
pyflakes.enable = false
pylint.enable = false
rope_autoimport.enabled = true
rope_autoimport.code_actions.enabled = true
rope_autoimport.completions.enabled = false
yapf.enable = false

# [language-server.ruff.config.settings.lint]
# select = [ "ALL" ]
# ignore = [
#   "ERA001", # Commented-out code
#   "ANN", # Type annotation
#   "D", # Docstring
# ]

[language-server.rust-analyzer.config.rust-analyzer]
check.command = "clippy" 
